#Duration of invulnerability after respawn in seconds
respawn-protection: 10
global-spawn:
  ==: org.bukkit.Location
    world: world
    x: 0.0
    y: 101.0
    z: 0.0
    pitch: 0.0
    yaw: 0.0