name: UpgradePvP
version: 1.0
main: upgradepvp.main.Main
author: Smart123s
commands:
  UpgradePvpTest:
    usage: /<command>
    description: A test command for UpgradePvp
    aliases: [upt]
  Shop:
    usage: /<command>
    description: Fix the shop item.
  Balance:
    usage: /<command> [player]
    description: Check your balance.
    aliases: [bal]
  Safe:
    usage: /<command> <amount|all>
    description: Move money to Safe Balance.