#Duration of invulnerability after respawn in seconds
respawn-protection: 10

# Database connection settings
database-user: "username"
database-password: "password"
database-url: "jdbc:mysql://localhost:3306/database"
