#Duration of invulnerability after respawn in seconds
respawn-protection: 10

# Automatically join players to a game when they connect to the server
# Provide the name of the map
auto-join-map: "none"

# Database connection settings
database-user: "username"
database-password: "password"
database-url: "jdbc:mysql://localhost:3306/database"
